#!/bin/bash
#
#chkconfig: 235 99 01
#description: Starts and stops TCPWebLog-Server

#==============================================================================+
# File name   : tcpweblog_server
# Begin       : 2012-04-12
# Last Update : 2012-09-18
# Version     : 3.2.3
#
# Description : Init script to execute TCPWebLog-Server.
#
# Website     : https://github.com/fubralimited/TCPWebLog
#
# Author: Nicola Asuni
#
# (c) Copyright:
#               Fubra Limited
#               Manor Coach House
#               Church Hill
#               Aldershot
#               Hampshire
#               GU12 4RQ
#				UK
#               http://www.fubra.com
#               support@fubra.com
#
# License:
#    Copyright (C) 2012-2012 Fubra Limited
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    See LICENSE.TXT file for more information.
#==============================================================================+

# configuration file
CONFIG_FILE="/etc/tcpweblog_server.conf"

# load parameters from configuration file
if [ -f $CONFIG_FILE ] ; then
	. $CONFIG_FILE
fi

# command
CMD="$PATH_TCPRECEIVER $LOGSERVER_PORT $MAX_CONNECTIONS $ROOT_DIR"
LOCKFILE=/var/lock/subsys/tcpweblog_server
RETVAL=0

# get SystemV Init function library.
if [ -f /etc/init.d/functions ] ; then
	. /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
	. /etc/rc.d/init.d/functions
else
	exit 1
fi

# Start the service
start() {
	if test -f $LOCKFILE ; then
		# check if the process is running
		if [ ! -z "`ps ax | grep -v grep | grep $PATH_TCPRECEIVER`" ]; then
			echo -n $"Service is Already Running."
			echo
			return
		else
			# delete the orphan lock file
			rm -f $LOCKFILE
		fi
	fi
	echo -n $"Starting TCPWebLog-Server: "
	#start the process
	$CMD
	RETVAL=$?
	[ $RETVAL = 0 ] && touch $LOCKFILE && success || failure
	echo
	return $RETVAL
}

# Restart the service
stop() {
	echo -n $"Stopping TCPWebLog-Server: "
	# check if the process is running
	if [ ! -z "`ps ax | grep -v grep | grep $PATH_TCPRECEIVER`" ]; then
		# kill the process
		killproc $PATH_TCPRECEIVER
		RETVAL=$?
	else
		failure $"TCPWebLog-Server stop"
	fi
	echo
	rm -f $LOCKFILE
	return $RETVAL
}

### main logic ###
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status $PATH_TCPRECEIVER
		RETVAL=$?
		;;
	restart|reload)
		stop
		start
		;;
	condrestart)
		if test -f $LOCKFILE ; then
			stop
			start
		fi
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
		RETVAL=2
		[ "$1" = 'usage' ] && RETVAL=0
esac
exit $RETVAL

#==============================================================================+
# END OF FILE
#==============================================================================+
